pipeline:
  test:
    image: ruby:2.4
    commands:
      - bundle install --path bundler
      - bundle exec rspec spec/
  build_xenial:
    image: ubuntu:xenial
    environment:
      - CPPFLAGS=-P
    commands:
      - apt-get update -y
      - apt-get install -y -q squashfs-tools build-essential ruby bison ruby-dev git-core curl
      - curl -L http://enclose.io/rubyc/rubyc-linux-x64.gz | gunzip > /usr/local/bin/rubyc
      - chmod +x /usr/local/bin/rubyc
      - gem install bundler
      - bundle install --path bundler
      - rubyc -o kupo kupo
      - ./kupo version --all
    when:
      event: tag