pipeline:
  test:
    image: ruby:2.4
    commands:
      - bundle install --path bundler
      - bundle exec rspec spec/ && bundle exec rubocop --fail-level A -S --format c --parallel
  create_gh_release:
    image: ubuntu:xenial
    secrets: [ github_token ]
    commands:
      - ./build/drone/create_release.sh
    when:
      event: tag
  build_xenial:
    image: ubuntu:xenial
    secrets: [ github_token ]
    environment:
      - CPPFLAGS=-P
    commands:
      - ./build/drone/ubuntu_xenial.sh
    when:
      event: tag
  release_binary:
    image: plugins/s3
    secret: [ access_key, secret_key ]
    bucket: pharos-cluster-binaries
    region: eu-west-1
    source: "pharos-cluster-linux-amd64-${DRONE_TAG##v}"
    target: /
    when:
      event: tag